feat: added configurability (`.gcmconfig.yml`) to use accross teams  and validation .
veritem/gcm pull request #2
Opened 2023-10-09 19:35 UTC by regisrex

### Changes and features
- gcm command now reads (`.gcmconfig.yml`) to get types and scopes used in the repo and it also creates the file in case it isn't there
- commit types and scopes used in creating commit messages are the ones configured in `.gcmconfig.yml` only, otherwise, the program panics!
- also beautified the dialog, et cetera.

full description of the current version in README.md

2023-10-13 00:12 UTC, veritem requested changes
Thank you so much brother. I'm grateful that you took your time to write all this code. I'm impressed.

For this config file do you think it'll be configured by project, whole computer configuration or both? what do you think?

2023-10-13 00:12 UTC, veritem commented on src/cli.rs
> +    let comm_scope = match commit_scope() {
We can rewrite this better to reduce the number of times we write `String:from("")`. It's repetitive. A match expression here would be much simpler.

2023-10-13 00:12 UTC, veritem commented on test
> +dfdsf
this file should be removed imo

2023-10-13 00:12 UTC, veritem commented on src/utils/mod.rs
> +    if git_status_stdout.contains("no changes added to commit")
no need for `||` right?

2023-10-13 00:12 UTC, veritem commented on src/utils/mod.rs
> +    let default_config: GcmConfig = GcmConfig {
can we write `default_config` and `default_config_file` in on variable please. It looks repetitive to me.

2023-10-13 00:13 UTC, veritem commented on src/utils/mod.rs
> +    if git_status_stdout.contains("no changes added to commit")
you're comparing one variable against it's self

2023-10-13 05:26 UTC, regisrex commented
> Thank you so much brother. I'm grateful that you took your time to write all this code. I'm impressed.
> 
> For this config file do you think it'll be configured by project, whole computer configuration or both? what do you think?

By project, just like how you may configure you `.gitignore` or `eslint` in a project

2023-10-13 05:47 UTC, regisrex commented on src/utils/mod.rs
> +    let default_config: GcmConfig = GcmConfig {
That's a good idea, I can use `default_config_file`, to build `default_config`

2023-10-13 05:57 UTC, regisrex commented on test
> +dfdsf
even `main_old.rs`

2023-10-13 06:34 UTC, regisrex commented
changes done @veritem , 
you can review again

2023-10-13 21:43 UTC, veritem requested changes
One more thing togo

2023-10-13 21:43 UTC, veritem commented on src/utils/mod.rs
> +    };
can we write this into `create_and_or_read_config` when we can't find for reading. My understanding is that this will always created when this function is created.

2023-10-14 00:18 UTC, regisrex commented
I'm not actually getting the point well but what I did is to handle both cases in the same fn

2023-10-14 02:06 UTC, veritem approved these changes
Thank you!

2023-10-14 02:06 UTC, merged